<?php 

use GuzzleHttp\Exception\GuzzleException;
use Drupal\Core\Entity\EntityInterface;


/**
 * Implements hook_entity_update().
 */
function seeds_nextjs_entity_update(EntityInterface $entity) {
  $allow_clearing = &drupal_static('seeds_nextjs_allow_clearing');
  $allow_clearing = TRUE;
}

/**
 * Implements hook_rebuild().
 */
function seeds_nextjs_rebuild() {
  $flush_cache_on_rebuild = (bool) \Drupal::config('seeds_nextjs.settings')->get('flush_cache_on_rebuild');

  if (!$flush_cache_on_rebuild) {
    return;
  }

  /** @var \Drupal\seeds_headless_helper\SeedsNextJsRequesterInterface $requester */
  $requester = \Drupal::service('seeds_headless_helper.requester');

  try {
    $requester->request('/api/flush-cache', 'POST');
  } catch (GuzzleException $e) {
    \Drupal::logger('seeds_nextjs')->error($e->getMessage());
    \Drupal::messenger()->addError(t('Failed to flush the cache in NextJS server.'));
  }
}
